name: Build Minecraft Mod

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip and prepare project
        run: |
          if ls *.zip 1> /dev/null 2>&1; then
            unzip -o *.zip
          fi
          BUILD_PATH=$(find . -name "build.gradle" -not -path "./build.gradle" | head -n 1)
          if [ -n "$BUILD_PATH" ]; then
            DIR=$(dirname "$BUILD_PATH")
            echo "Encontrado en $DIR, moviendo a la raíz..."
            cp -r "$DIR"/* .
          fi

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.8'

      - name: Build Mod with Gradle
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x gradlew
            ./gradlew build
          else
            gradle build
          fi

      - name: Upload Mod Jar
        uses: actions/upload-artifact@v4
        with:
          name: mod-compilado
          path: build/libs/*.jar
